### ISSUE TITLE
Make the window draggable

### ISSUE THREAD

**Issue by MattLish** [UltimateSkyrim/ultskylauncher#38]
It is currently not possible to drag the application window, a menu bar needs adding at the top to make dragging the window easier.

[Documentation](https://github.com/electron/electron/blob/master/docs/api/frameless-window.md#draggable-region) on how to do this.

### ~Outstanding questions~
- ~Does this need adding to the Figma design?~
Answered below

**Comment by RingComics** [comment]
I don't think this needs to be added to the figma, as the draggable region can be invisible with an arrow cursor to indicate it can be moved. This was in an earlier version, and was forgotten about in the UI overhaul I imagine

**Comment by MattLish** [comment]
Okay, we can add an invisible title/menu bar that can be dragged. We might need an actual visible one, but we can see about that in the future.
