### ISSUE TITLE
Patreon Integration

### ISSUE THREAD

**Issue by RingComics** [UltimateSkyrim/ultskylauncher#6]
With the Patrons being on the home page, they aren't also needed in the footer.
- [x] Remove footer

Integrate the news and patrons

- [x] Add "news" from Patreon
- [x] Add "Patron list" from Patreon

Patreon API: https://ultsky.phinocio.com/api/patreon

```
interface Patron {
    name: string
    tier: "Patron" | "Super Patron"
}

interface Post {
    title: string
    content: string
    published: string
    url: string
}

interface PatreonsResponse {
    patrons: Patron[]
    posts: Post[]
}

```

**Comment by MattLish** [comment]
Progress for adding Patreon list tracked in https://github.com/UltimateSkyrim/ultskylauncher/tree/feat/patreon-list

**Comment by MattLish** [comment]
Patreon list has been added with #44

**Comment by MattLish** [comment]
Progress tracked here https://github.com/UltimateSkyrim/ultskylauncher/tree/feat/news-list

Blocked by #46 because the `p` tag is used in news and this style is globally set.

**Comment by MattLish** [comment]
I was incorrectly trying to render the content instead of the title. Titles shouldn't contain HTML so this is no longer blocked.

**Comment by MattLish** [comment]
Outstanding work:

- Open links in a new browser window (Electron doesn't handle this by default)
- Apply colours to tags (news and devstream should be coloured as per the design and other tags should be grey)
- Fix issue where the date bleeds into the background 
![image](https://user-images.githubusercontent.com/5766291/112398506-4871d900-8cfc-11eb-89e6-9ea5c4b9c529.png)
- Fix misalignment of tags 
![image](https://user-images.githubusercontent.com/5766291/112398530-54f63180-8cfc-11eb-8a80-0cdc19428f5a.png)

**Comment by MattLish** [comment]
Blocked by #47
