### ISSUE TITLE
Merge AS with UltSkyLauncher

### ISSUE THREAD

**Issue by RingComics** [UltimateSkyrim/ultskylauncher#9]
- [ ] Move over back-end code
- [ ] Change generic functions to be UltSky specific
- [ ] Remove unneeded functionality

**Comment by MattLish** [comment]
Is there any way this can be broken down any further?
Is there specific parts of the Be code that can be moved over bit by bit?

**Comment by MattLish** [comment]
This has been merged. Any additional functionality can be added as new issues.
